### PR TITLE
Add progress bar for downloads and some minor code optimization

### PR DESCRIPTION
**Pull request by Infiniteez**
Using BitsTransfer module (which provides a native progress bar and localized text) instead of WebClient.DownloadFile

Compatibility note: BitsTransfer is natively supported in Windows 10 since the 20H1 update, it shouldn't cause problems for the vast majority of users (that update came out over a year and a half ago in May 2020)

### CODE REVIEW

**Comment by mrpond** [comment]
Hi, please make check condition. we want backward compatibility with windows 7 too.

**Review by mrpond — CHANGES_REQUESTED** [review]
Hi, please make check condition. we want backward compatibility with windows 7 too.

**Review by Nuzair46 — CHANGES_REQUESTED** [review]
BitsTransfer will only work with Windows 10 above 20H1, its not ideal since there are a lot of users with Windows older than that.

**Comment by NguyenASang** [comment]
My friend is using Window 7 so if the change is added it will make him can't use this anymore so find another way to optimize it.

**Comment by Infiniteez** [comment]
Working on a better solution

**Pull request closed without merging**
