### PR TITLE
Re-Patcher after update

### PR DESCRIPTION
**Pull request by SmartManoj**

### CODE REVIEW

**Comment by rednek46** [comment]
The current BlockTheSpot.bat does the same. There is no need for another patcher.
this is what BlockTheSpot does.
- Always install the latest patch.
- Detects Spotify from windows store and asks for uninstallation.
- Installs latest Spotify if you don't have it.
- Repatches the Spotify with the latest BlockTheSpot.
Since the ReBlockTheSpot.bat is already included with the current BlockTheSpot.bat, there is no reason to merge.

If you are interested to modify and work on the current patcher, you can do so in [this repo](https://github.com/rednek46/BlockTheSpot)

These are my future ideas for this patcher.
- Updates Spotify to the latest if you have the older version.
- Friendly UI

**Comment by SmartManoj** [comment]
Spotify will auto-update. The old patch file may work. So, we won't need to download it again. If not we will report.

**Comment by rednek46** [comment]
Yea but still its unwanted. since anyone who uses Spotify with BlockTheSpot will have access to Internet. And its not like the downloaded patch is a huge file. its merely 2MB.   

The script in this pull avoids download for re-patch, but that's not worth when considering to update users about the newer Patch or the person who has to run normal BTS incase the older patch he has doesn't work. Hope I made this clear.

**Comment by SmartManoj** [comment]
https://github.com/mrpond/BlockTheSpot/issues/92#issuecomment-742476515
Even the 2MB is a waste of bandwidth also takes a minute to complete the process.
With [this](https://github.com/mrpond/BlockTheSpot/issues/92#issuecomment-742478882), one can know when to re-patch.

**Pull request closed without merging**
