### PR TITLE
Fix PS v7 compatibility

### PR DESCRIPTION
**Pull request by KUTlime**
Fix PS v7 compatibility

This fixes PowerShell +v7.0.0 compatibility issue by loading explicitly AppX module into the session with the compatibility flag.

## Note
The install PS script is a rubbish. If you are interested in refactoring into a proper, maintainable code, please, let me know.

### CODE REVIEW

**Review by Nuzair46 — APPROVED** [review]

**Comment by KUTlime** [comment]
> 
> 
> Please tell me how to make this code compatible with earlier versions of powershell (2,3,4)?

Why you want this??? It doesn't make any sense.

**Comment by Nuzair46** [comment]
> Please tell me how to make this code compatible with earlier versions of powershell (2,3,4)?

If you are wondering on how to use the script on Windows 7, then I think you can just remove the code block that checks for Store version version of Spotify. 
It may work after that, but its unlikely that older powershell can run the script without major changes.
But it is possible to make a batch script without any powershell stuff to make it work on windows 7.

**Comment by KUTlime** [comment]
> 
> 
> > Please tell me how to make this code compatible with earlier versions of powershell (2,3,4)?
> 
> If you are wondering on how to use the script on Windows 7, then I think you can just remove the code block that checks for Store version version of Spotify.
> It may work after that, but its unlikely that older powershell can run the script without major changes.
> But it is possible to make a batch script without any powershell stuff to make it work on windows 7.

This is a terrible idea. PowerShell 2, 3, 4 are not supported by years by Microsoft, event Windows 7 has PowerShell 5.1.

**Comment by amd64fox** [comment]
> > Please tell me how to make this code compatible with earlier versions of powershell (2,3,4)?
> 
> Why you want this??? It doesn't make any sense.

I want this script to work on win7, win8.

**Comment by amd64fox** [comment]
> This is a terrible idea. PowerShell 2, 3, 4 are not supported by years by Microsoft, event Windows 7 has PowerShell 5.1.

i updated in win7 powershell to version 5.1 and this script still doesn't work

**Comment by amd64fox** [comment]
> > Please tell me how to make this code compatible with earlier versions of powershell (2,3,4)?
> 
> If you are wondering on how to use the script on Windows 7, then I think you can just remove the code block that checks for Store version version of Spotify.
> It may work after that, but its unlikely that older powershell can run the script without major changes.
> But it is possible to make a batch script without any powershell stuff to make it work on windows 7.

I'll try, but what line numbers are we talking about?

**Comment by Davoleo** [comment]
@amd64fox 

If you get some issues while invoking this powershell line: https://github.com/mrpond/BlockTheSpot/blob/master/BlockTheSpot.bat#L2
Try using this batch script instead: 
```bat
@echo off
powershell -Command "& {[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12}"; "& {Invoke-WebRequest -UseBasicParsing 'https://raw.githubusercontent.com/mrpond/BlockTheSpot/master/install.ps1' | Invoke-Expression}"
pause
exit
```

**Comment by KUTlime** [comment]
> 
> 
> > This is a terrible idea. PowerShell 2, 3, 4 are not supported by years by Microsoft, event Windows 7 has PowerShell 5.1.
> 
> i updated in win7 powershell to version 5.1 and this script still doesn't work

How about report the reason of the failure, hmm? Line invocation, your PowerShell version, dump related system setup etc.?

**Comment by amd64fox** [comment]
@Davoleo  @KUTlime  
Windows 7
PowerShell 2
> If you get some issues while invoking this powershell line: https://github.com/mrpond/BlockTheSpot/blob/master/BlockTheSpot.bat#L2

Did not work
Снимок экрана 2021-07-26 202121

> Try using this batch script instead:
> 
> ```batchfile
> @echo off
> powershell -Command "& {[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12}"; "& {Invoke-WebRequest -UseBasicParsing 'https://raw.githubusercontent.com/mrpond/BlockTheSpot/master/install.ps1' | Invoke-Expression}"
> pause
> exit
> ```

Did not work
Снимок экрана 2021-07-26 2902121

**Pull request merged**
