### PR TITLE
Patch to remove ad placeholder

### PR DESCRIPTION
**Pull request by compilerdeceiver397**
Based on https://github.com/mrpond/BlockTheSpot/issues/150#issuecomment-903240079

Not sure if this is "safe" but it seems to work nicely.

I'm also not sure about how to do the backup, because if the script is run twice, it will silently overwrite the older one...

### CODE REVIEW

**Comment by Nuzair46** [comment]
Will this be compatible with a future update without needing to update again?

**Comment by Nuzair46** [comment]
I will keep this on hold for now until we are sure that this method can last for at least a couple of updates. Because its not ideal to keep updating the script everytime Spotify updates.

**Comment by compilerdeceiver397** [comment]
Just checked `1.1.46.916.g416cacf1-a` (released 17/11/2020) and the property does exist, but it's inside a lambda:
```js
(e=>e.ads.leaderboard.isEnabled)
```

I just updated the regex to match both `}` and `)`, and it still works.

**Comment by Nuzair46** [comment]
Great, I will merge it.

**Pull request merged**
