### PR TITLE
change the parameters to bool to support un-attended calling of the script

### PR DESCRIPTION
**Pull request by sharunkumar**
Example:

```ps1
.\install.ps1 -UninstallSpotifyStoreEdition $false -UpdateSpotify $false -RemoveAdPlaceholder $true
```

### CODE REVIEW

**Review by Nuzair46 — APPROVED** [review]

**Comment by Nuzair46** [comment]
@KUTlime Please review.

**Comment by KUTlime** [comment]
A `switch` type parameter is just boolean which acts like `true` when provided, and `false` otherwise.

This system is just a simplification which is natural to the PowerShell ecosystem. 

A `switch` type parameter can be set to the `false` value explicitly by `-UninstallStoreVersion:$false`.

**My recommendation is close with no merge.**

**Comment by sharunkumar** [comment]
> A `switch` type parameter can be set to the `false` value explicitly by `-UninstallStoreVersion:$false`.

This doesn't work.

image

**Comment by KUTlime** [comment]
@sharunkumar I said that before on other PRs like #333 - it is better if you **clearly and extensively articulate the problem** which you have. That is the mandatory start from which any PR can be reviewed.

If you can provide enough details, feel free to open an issue, put the details there and I will investigate the problem.

**Pull request closed without merging**
