### PR TITLE
Update uninstall.bat

### PR DESCRIPTION
**Pull request by Daksh777**

### CODE REVIEW

**Review by Davoleo — COMMENTED** [review]
That is needed for people who have tried to restore the OLD UI in the past via the old install script, as such I wouldn't remove this

**Comment by Daksh777** [comment]
> That is needed for people who have tried to restore the OLD UI in the past via the old install script, as such I wouldn't remove this

In the new script, we are no longer removing the old UI or the upgrade button using the script, so it doesn't make sense to include it in the uninstall script.

**Comment by Davoleo** [comment]
It makes sense because there would be no easy way for people who experience the black screen bug to fix if we remove it.
Because THAT'S what happens when spotify updates and the old UI injection remains active

**Comment by Daksh777** [comment]
I'll leave it up to the members of this repository now

**Comment by Nuzair46** [comment]
Hey @Daksh777 I cant pull this PR right now since in the Discord many users come with issues related to using the Old bat script.
Until the numbers are reduced and majority or all of the bat script users update the script to the latest, Im not merging this.
The reason being the one I said.
Also, the extra lines in the script doesn't do anything if they have never used the old bat script. I hope its clear.

**Pull request closed without merging**
