### PR TITLE
BlockTheSpot.bat now allows the chrome_elf.dll false threat preventing a quarantine. And readme updated.

### PR DESCRIPTION
**Pull request by rednek46**

### CODE REVIEW

**Comment by mrpond** [comment]
I don't know what these magic number in PowerShell script mean
where it come from?

**Comment by rednek46** [comment]
@mrpond that number is just the threat id that Microsoft uses to identify and mark a certain threat. It can be obtained running the command Get-MpThreatDetection and it will return all the past detected threat in my system. And the thread id is same for all, so i just used it to allow the threat with that id in ms defender.

**Comment by rednek46** [comment]
powershell -Command "Start-Process PowerShell -Argumentlist 'Add-MpPreference -ThreatIDDefaultAction_Action Allow -ThreatIDDefaultAction_Ids 2147749373' -Verb RunAs"

What this line does is open a powershell as admin. Only this single line is ran as admin in the entire script. The line sets a default action "Allow" to any detection of the threat by tue given id, 2147749373 in our case with chrome_elf.dll. This line only changes the default Action to that threat id and it doesn't exclude the threat all together, so the scan for this threat still works but it doesn't remove the file. The detected files are always shown as allowed in ms defender which can be removed or change the action within the defender.

**Comment by rednek46** [comment]
I have created another [branch](https://github.com/rednek46/BlockTheSpot/tree/detection). Here the repo is same but the threat allowing command is in a separate batch file named FalseDetectionFix.bat . It does the same as above with just one extra step.

**Comment by mrpond** [comment]
OK, thank for clarify this. 
I'm OK with pull request, but let's wait MS team a little bit.

**Comment by rednek46** [comment]
> OK, thank for clarify this.
> I'm OK with pull request, but let's wait MS team a little bit.

Okay 👍

**Comment by mrpond** [comment]
Hi please help me test 2020.04.21 release, I think it no longer detect as virus now.

**Pull request closed without merging**
